# Generated by Django 5.2.5 on 2025-10-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن اصلی')),
                ('preprocessed_text', models.TextField(verbose_name='متن پردازش\u200cشده')),
                ('true_label', models.IntegerField(choices=[(0, 'خوشحال'), (1, 'ناراحت')], verbose_name='برچسب واقعی')),
                ('predicted_label', models.IntegerField(choices=[(0, 'خوشحال'), (1, 'ناراحت')], verbose_name='برچسب پیش\u200cبینی\u200cشده')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'بازخورد تحلیل احساس',
                'verbose_name_plural': 'بازخوردهای تحلیل احساس',
            },
        ),
        migrations.CreateModel(
            name='SentimentFeedbackArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن اصلی')),
                ('preprocessed_text', models.TextField(verbose_name='متن پیش\u200cپردازش شده')),
                ('true_label', models.IntegerField(verbose_name='برچسب واقعی')),
                ('predicted_label', models.IntegerField(verbose_name='برچسب پیش\u200cبینی')),
                ('timestamp', models.DateTimeField(verbose_name='زمان ثبت')),
                ('archived_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان بایگانی')),
            ],
            options={
                'verbose_name': 'بایگانی تحلیل احساس',
                'verbose_name_plural': 'بایگانی بازخوردهای تحلیل احساس',
            },
        ),
    ]
